# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy to Firebase
on:
  push:
    branches: 
      - master 

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: CI='' npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
    env:
      REACT_APP_FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}} 
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}} 
      REACT_APP_FIREBASE_DATABASE_URL: ${{secrets.FIREBASE_DATABASE_URL}} 
      REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}} 
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}} 
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}} 
      REACT_APP_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}} 
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}} 
      REACT_APP_TMDB_API_KEY: ${{secrets.TMDB_API_KEY}} 
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}} 
